// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Soldini_TestiMusicali.Data;

namespace Soldini_TestiMusicali.Migrations
{
    [DbContext(typeof(Soldini_TestiMusicaliContext))]
    [Migration("20200410105856_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Soldini_TestiMusicali.Models.Lyric", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("artist");

                    b.Property<DateTime>("release_date");

                    b.Property<string>("song");

                    b.Property<string>("text");

                    b.Property<string>("writer");

                    b.HasKey("id");

                    b.ToTable("Lyric");
                });
#pragma warning restore 612, 618
        }
    }
}
